name: studentapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.

version: 1.4.700
environment:
  sdk: ">=3.0.2 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  app_settings: ^5.1.1
 

 
  cupertino_icons: ^1.0.2
  dart_std: null
 
  dio: ^5.3.2
  
  dropdown_button2: ^1.4.0
 
  flutter_slidable: ^3.1.1
  file_picker: ^6.0.0 
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: any
  geolocator: ^10.0.1
  get_it: ^7.2.0
  image_picker: ^1.0.4
  flutter_map: any
  intl: ^0.17.0
  local_auth: ^2.0.2
  logger: ^1.1.0
  lottie: ^2.6.0
  path_provider: ^2.1.1
  permission_handler: ^10.0.0
  pretty_dio_logger: ^1.1.1
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.1.1
  sqflite: ^2.0.0+4
  the_validator: ^2.0.0
  timer_count_down: ^2.2.0
  tuple: ^2.0.2
  url_launcher: ^6.1.14
  flutter_switch: ^0.3.2
  flutter_widget_from_html: ^0.14.9
  cron: ^0.5.0
  google_fonts: ^4.0.4
  water_drop_nav_bar: ^2.2.2
  mocktail: ^1.0.1
  equatable: ^2.0.5
  flutter_animate: ^4.5.0
  mockito: ^5.4.4
  dartz: ^0.10.1

dev_dependencies:
  build_runner: any
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/pngs/
    - assets/pngs/2x/
    - assets/pngs/3x/
    - assets/svgs/
    - assets/anim/
    - lib/core/data/mock/student.json

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSans3-ExtraBold.ttf
          weight: 900
